Controllers/GaleriaController.cs
using App.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace App.Controllers;

public class GaleriaController : Controller
{
    private readonly DatabaseContext db;

    public GaleriaController(DatabaseContext db)
    {
        this.db = db;
    }

    public IActionResult Index()
    {
        var galerias = db.Galerias.AsNoTracking().ToList();
        return View(galerias);
    }

    public IActionResult Cadastrar()
    {
        return View();
    }

    [HttpPost, ValidateAntiForgeryToken]
    public IActionResult Cadastrar(Galeria galeria)
    {
        if (ModelState.IsValid)
        {
            db.Galerias.Add(galeria);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        return View(galeria);
    }

    public IActionResult Alterar(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        var galeria = db.Galerias.Find(id);
        if (galeria == null)
        {
            return NotFound();
        }
        return View(galeria);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public IActionResult Alterar(Galeria galeria)
    {
        if (ModelState.IsValid)
        {
            db.Entry(galeria).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        return View(galeria);
    }

    public IActionResult Excluir(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }
        var galeria = db.Galerias.Find(id);
        if (galeria == null)
        {
            return NotFound();
        }
        return View(galeria);
    }

    [HttpPost, ValidateAntiForgeryToken]
    [ActionName("Excluir")]
    public IActionResult ExecutarExclusao(int? id)
    {
        var galeria = db.Galerias.Find(id);
        if (galeria == null)
        {
            return NotFound();
        }
        db.Galerias.Remove(galeria);
        db.SaveChanges();
        return RedirectToAction("Index");
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap5/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/lib/bootstrap-icons/font/bootstrap-icons.min.css">
    <link href="/lib/lightbox2/dist/css/lightbox.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="/css/estilos.css">
    <title>Galeria de Imagens</title>
</head>

<body style="padding-bottom: 80px" class="mb-3">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="/">Galeria de Imagens</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMain">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarMain">
                <div class="navbar-nav ms-auto">
                    <a class="nav-link" asp-controller="Home" asp-action="Index"
                        asp-link-class="link-ativo">Principal</a>
                    <a class="nav-link" asp-controller="Galeria" asp-action="Index"
                        asp-link-class="link-ativo">Galerias</a>
                </div>
            </div>
        </div>
    </nav>

    <div class="container mt-2">
        <h1>@Html.Raw(ViewBag.Titulo)</h1>
        <hr>
        @RenderBody()
    </div>

    <div class="text-light bg-dark p-3 fixed-bottom text-center">
        TagHelpers&copy; @DateTime.Now.Year.ToString()<br>
        Todos os direitos reservados
    </div>

    @RenderSection("Scripts", false)
    <script src="/lib/lightbox2/dist/js/lightbox-plus-jquery.min.js"></script>
    <script>
        lightbox.option({
            'albumLabel': 'Imagem %1 de %2'
        });
    </script>
</body>

</html>